### ISSUE TITLE
Add new imageset

### ISSUE THREAD

**Issue by enmust** [geocollections/sarv-file-upload#24]
Users should be able to add new imageset. Currently form with three fields is made and accessible using 'plus' button in photo archive upload.

**Comment by urtson** [comment]
New imageset_number should somehow be checked for names already in use to avoid duplicate names. Right now the field is even not set to unique=true in models but setting this would anyway throw some server error which is inconvenient to show.
Is it possible to make it in vue so that user gets fast feedback while typing?

**Comment by urtson** [comment]
New imagesets can now be created but imageset_number is not sent: in query response it shows "imageset_number: undefined"

**Comment by enmust** [comment]
removed undefined bug

**Comment by enmust** [comment]
I believe I can and should add some feedback which tells if imageset_number already exists in imageset table. 
Also I think if user still ignores it or somehow feedback request is too slow API should return some response like 'Imageset already exists' or just adds imageset but appends it with string '(copy 1)' or something.

**Comment by enmust** [comment]
Looks like imagset works, closing it
