### ISSUE TITLE
Specimen field on specimen image upload

### ISSUE THREAD

**Issue by urtson** [geocollections/sarv-file-upload#46]
For batch specimen image uploads, API can get the specimen_id from file name if it is named appropriately. The 'specimen' field is then left blank. If filled in, specimen_id is taken from the form.

Currently can't do  it automatically as the 'specimen' field can not be empty

**Comment by enmust** [comment]
Should I make 'specimen' field so it can be empty, but then there is a possibility that file name is incorrectly named and 'specimen' field is empty. 

But there are some ways to fix it:

1. User can just enter file if it is named correctly then the relation to specimen is made else it is not made. If relation was not made then user can go to edit view to fill in the specimen field to add relation. (In my opinion not the best way, because first of all user needs do to too many clicks and secondly how does user know if relation was made or not)

2. User enters file and then the file name is used in specimen field, if it gets result then specimen field is filled else user needs to fill it. If file is correctly named then it would remove the need to manually fill the specimen field but this means specimen field can't be empty. (In my opinion this seems like the most comfortable and fastest way to user) 

Depends what 'appropriately' named file means, if it is some kind of regex the file name should follow then I can just send the data and relation is made automatically in back-end.

**Comment by urtson** [comment]
Yes, make the field  empty.

If a batch of files is uploaded, API skips the files for which the specimen id can not be read from file name and gives an error with the list of these file names. These files will not be uploaded and user must start over one by one or first rename files correctly.
The other way  to do it in API is to upload all files and show the list where relations were not made, user can choose right specimen manually in edit view. I prefer first solution.

In case of single file with incorrect name and empty specimen field the result is the same.

File name pattern is specimenid_filenumber i.e everything before underscore must match an existing specimen id. Also, filtering on database (institution) is made simultaneously as different institutions can have matching specimen ids.

Automatically filling in the specimen field in vue would work for single file but not for batch

**Comment by enmust** [comment]
Specimen field can now be empty

**Comment by enmust** [comment]
I think this can be closed, reopen if not
